---
title: "Project 2"
author: "Yuhan Xiao"
output: html_document
date: "2023-10-01"
---

## Background 
```{r message = FALSE}
library(here)
library(tidyverse)
library(lubridate)
library(ggplot2)
```

## Part 1: Fun with functions
#### Part 1A: Exponential transformation
```{r part_1A}
# define a function Exp(x,k) that computes the exponential of a number using the truncated series expansion
# parameters
# x : the number to be exponentiated
# k : the number of terms to be used in the series expansion beyond the constant 1, k is always >= 1
Exp <- function(x,k) {
  output = 1
  count = 1
  while (count <= k) {
    output = output + (x ^ count) / factorial(count)
    count = count + 1
  }
  output
}

# an example using function Exp(x,k)
Exp(2,15)
# compare with actual exp() function in R
exp(2)
```

#### Part 1B: Sample mean and sample standard deviation
```{r part_1B}
# define a function sample_mean(x) that calculates the sample average for a vector of data of length N
# parameter
# x : a vector of numbers of length N
sample_mean <- function(x) {
  N = length(x)
  output = sum(x) / N
  output
} 

# define a function sample_sd(x) that calculates the sample standard deviation for a vector of data of length N
# parameter
# x : a vector of numbers of length N
sample_sd <- function(x) {
  N = length(x)
  avg = sum(x) / N
  output = sqrt(sum((x - avg) ^ 2) / (N - 1))
  output
}

# an example using functions sample_mean(x) and sample_sd(x)
x = c(1,2,3,4)
sample_mean(x)
sample_sd(x)
# compare with actual mean() and sd() functions in R
mean(x)
sd(x)
```

#### Part 1C: Confidence intervals
```{r part_1C}
# define a function calculate_CI(x, conf) that calculates the confidence interval for a vector of data of length N
# parameter
# x : a vector of numbers of length N
# conf : = (1-alpha) allows the confidence interval to be adapted for different alpha, with a default value of 0.95
calculate_CI <- function(x, conf = 0.95) {
  alpha = 1 - conf
  N = length(x)
  degrees_freedom = N - 1
  t_score = qt(p = alpha / 2, df = degrees_freedom, lower.tail = FALSE)
  avg = mean(x)
  se = sd(x) / sqrt(N)
  output = c(avg - t_score * se, avg + t_score * se)
  names(output) = c("lower_bound", "upper_bound")
  output
}

# examples using calculate_CI(x, conf)
x = c(1,2,3,4,5,6)
calculate_CI(x, 0.9)
calculate_CI(x, 0.5)
# compare with existing confint() function in R
dat <- data.frame(x = x)
fit <- lm(x ~ 1, dat)
## Calculate the confidence interval
confint(fit, level = 0.9)
confint(fit, level = 0.5)
```

## Part 2: Wrangling data
```{r part_2_setup}
# read in the following data from TidyTuesday
if (!file.exists(here("data", "tuesdata_rainfall.RDS"))) {
    tuesdata <- tidytuesdayR::tt_load("2020-01-07")
    rainfall <- tuesdata$rainfall
    temperature <- tuesdata$temperature

    # save the files to RDS objects
    saveRDS(tuesdata$rainfall, file = here("data", "tuesdata_rainfall.RDS"))
    saveRDS(tuesdata$temperature, file = here("data", "tuesdata_temperature.RDS"))
}

# load the datasets
rainfall <- readRDS(here("data", "tuesdata_rainfall.RDS"))
temperature <- readRDS(here("data", "tuesdata_temperature.RDS"))

# take a look at the data
glimpse(rainfall)
glimpse(temperature)
```

```{r part_2_tasks}
df <- rainfall %>%
  na.omit() %>% # drop any rows with NAs
  mutate(date = ymd(paste(year, month, day, sep = "-"))) %>% # create a new column that combines year, month, day
  select(-(month:day)) %>% # drop columns month and day
  mutate(city_name = toupper(city_name)) # convert city names to all upper case

# join this wrangled rainfall dataset with the temperature dataset
df <- df %>%
  inner_join(temperature, by = c("city_name", "date"), relationship = "many-to-many")

# take a look at the wrangled data
glimpse(df)
```

## Part 3: Data visualization
#### Part 3A: Plotting temperature data over time
```{r part_3A}
# filter out rows with years 2014 and onwards
data <- df %>%
  filter(year >= 2014)

# make a line plot of the max and min temperature over time for each city
data %>%
  ggplot(aes(x = date, y = temperature, color = temp_type)) +
  geom_line(linewidth = 1) +
  scale_colour_manual(values = c("#FAAB18", "#1380A1")) +
  facet_wrap(~city_name, nrow = 3, scales = "fixed") +
  labs(title = "Maximum and Minimum Temperature Changes Per City in 2014-2019", subtitle = "Cities in Australia are coldest around the middle of each year and warmest around the end of each year.\n Temperatures in Canberra fluctuate the most from about 40°C to -10°C.\n Sydney has the highest mininum temperature of about 5°C.", caption = "Yuhan Xiao", x = "Time (date)", y = "Temperature (Celsius)", color = "temp type") +
  theme_minimal(base_size = 14) +
  theme(plot.title = element_text(hjust = 0.5, vjust = 1, size = 15), 
        axis.text.x = element_text(angle = 45, hjust = 1),
        plot.background = element_rect(fill = "white"),
        text = element_text(family = "Times"))
```

#### Part 3B: Plotting rainfall over time
```{r part_3B}
# define a function that plots a histogram of rainfall distribution for a given city in a given year
# parameters
# city : the given city (all upper case)
# yr : the given year
# description
# My plot_rainfall function first checks if user inputs can be matched from the df dataset. If not, the function returns an error message. Then it filters out rows with years 2014 and onward. It checks if the combination of user inputs have measurements in the dataset. If not, it returns an error message. Otherwise, the function plots a histogram for the distribution of rainfall for a given city in a given year. It returns this plot.
plot_rainfall <- function(city, yr) {
  # check if user inputs are valid
  city_names <- unique(df$city_name)
  year_range <- unique(df$year)
  if (!(city %in% city_names)) {
    stop(paste(city, " does not exist in the dataset", sep = ""))
  } else if (!(yr %in% year_range)) {
    stop(paste(yr, " does not exist in the dataset", sep = ""))
  }
  
  # select data with the given city and year
  data <- df %>%
    filter(city_name == city, year == yr)
  # check if the combination of city and year has measurements
  if (nrow(data) == 0) {
    stop(paste("The combination of ", city, " and ", yr, " does not have measurements", sep = ""))
  }
  
  # plot the histogram
  hist_plot <- data %>%
    ggplot(aes(log(rainfall))) +
    geom_histogram(binwidth = 0.5, color = "#FAAB18", fill = "#FAAB18") +
    labs(title = paste("Distribution of Rainfall (Log Scale) for ",city, " in Year ", yr, sep=""), caption = "Yuhan Xiao", x = "Log(rainfall) (millimeters)", y = "Frequency (days)") +
    theme_minimal(base_size = 14) +
    theme(plot.title = element_text(hjust = 0.5, vjust = 1, size=15),
          text = element_text(family = "Times"))
  hist_plot
}

# an example of using plot_rainfall(city, yr)
plot_rainfall("PERTH", 2000) +
  labs(subtitle = "Most days had log(rainfall) between 0 to 3 millimeters")
```

## Part 4: Apply functions and plot
#### Part 4A
```{r part_4A}
# calculate sample mean, standard deviation, 95% confidence interval for the average rainfall per city by year
rain_df <- df %>% 
  filter(year >= 2014) %>%
  group_by(city_name, year) %>%
  summarize(rainfall_mean = sample_mean(rainfall),
         rainfall_sd = sample_sd(rainfall),
         rainfall_lower_bound = calculate_CI(rainfall)[1],
         rainfall_upper_bound = calculate_CI(rainfall)[2])
  
# take a look at the data
glimpse(rain_df)
```

#### Part 4B
```{r part_4B}
# plot the estimates of mean rainfall and the 95% confidence intervals for each city
rain_df %>%
  ggplot(aes(x = year, y = rainfall_mean)) +
  facet_wrap(~city_name, nrow=3, scales="fixed") +
  geom_point(color = "#FAAB18") +
  geom_line(color = "#FAAB18") +
  geom_errorbar(aes(ymin = rainfall_lower_bound, ymax = rainfall_upper_bound), width = 0.5, color = "#1380A1") +
  labs(title = "Estimates of Mean Rainfall and the 95% Confidence Intervals for Each City in 2014-2019", subtitle="Canberra has the least rainfall on average. It rains roughly the same throughout each year.\n Perth has the most rainfall on average. The amount of rainfall varies greatly within each year.\n ", caption="Yuhan Xiao", x = "Time (year)", y = "Average rainfall (millimeters)") + 
  theme_minimal(base_size = 14) +
  theme(plot.title = element_text(hjust = 0.5, vjust = 1, size=15),
          text = element_text(family = "Times"))
```